// EasyMakeover — curated style dataset
// Each item is tagged with occasions, weather buckets, style preferences, and presentations.
// `presentations` controls which user (feminine / masculine / androgynous) the item is shown to.
// Use `["any"]` as a shortcut for "works for anyone".

window.OCCASIONS = [
  { id: "wedding",   label: "Wedding",          emoji: "💒" },
  { id: "interview", label: "Job Interview",    emoji: "💼" },
  { id: "party",     label: "Party / Night Out",emoji: "🎉" },
  { id: "date",      label: "Date Night",       emoji: "💕" },
  { id: "brunch",    label: "Brunch",           emoji: "🥐" },
  { id: "casual",    label: "Casual Outing",    emoji: "👟" },
  { id: "festival",  label: "Festival",         emoji: "🪔" },
  { id: "work",      label: "Work / Office",    emoji: "🖥️" },
  { id: "beach",     label: "Beach Day",        emoji: "🏖️" },
  { id: "gym",       label: "Gym / Active",     emoji: "💪" },
];

window.WEATHERS = [
  { id: "sunny", label: "Sunny",  emoji: "☀️" },
  { id: "rainy", label: "Rainy",  emoji: "🌧️" },
  { id: "cold",  label: "Cold",   emoji: "❄️" },
  { id: "humid", label: "Humid",  emoji: "💧" },
];

window.STYLES = [
  { id: "simple",  label: "Simple",  emoji: "🌿", blurb: "clean & effortless" },
  { id: "comfy",   label: "Comfy",   emoji: "🧸", blurb: "easy & cosy" },
  { id: "stylish", label: "Stylish", emoji: "✨", blurb: "elevated everyday" },
  { id: "fancy",   label: "Fancy",   emoji: "👑", blurb: "go all out" },
];

window.PRESENTATIONS = [
  { id: "feminine",    label: "Feminine",    emoji: "♀" },
  { id: "androgynous", label: "Androgynous", emoji: "⚪" },
  { id: "masculine",   label: "Masculine",   emoji: "♂" },
];

// ----- MAKEUP / GROOMING -----
window.MAKEUP = [
  // Feminine makeup
  {
    name: "Natural Glow",
    emoji: "🌸",
    desc: "Tinted moisturizer, groomed brows, a swipe of mascara, peachy cheeks, balmy lip.",
    palette: ["#F5D8C8", "#E8A18C", "#B96D5D"],
    occasions: ["brunch","casual","interview","work","date","beach"],
    weather: ["sunny","humid","any"],
    styles: ["simple","comfy"],
    presentations: ["feminine"],
  },
  {
    name: "Matte Nude",
    emoji: "🤎",
    desc: "Polished matte base, neutral eye, defined brows, soft mocha lip — quietly powerful.",
    palette: ["#E8C8A0", "#B89070", "#704030"],
    occasions: ["interview","work","brunch"],
    weather: ["any","cold","humid"],
    styles: ["simple","stylish"],
    presentations: ["feminine"],
  },
  {
    name: "Dewy Minimal",
    emoji: "💧",
    desc: "Glass-skin glow, cream blush on the high points, glossy lid, slick lip.",
    palette: ["#FFE8DC", "#FFB8A0", "#E07060"],
    occasions: ["brunch","date","casual","beach"],
    weather: ["sunny","humid"],
    styles: ["comfy","stylish"],
    presentations: ["feminine"],
  },
  {
    name: "Soft Glam",
    emoji: "✨",
    desc: "Champagne lid, winged liner, lifted lashes, contoured cheeks, mauve-rose lip.",
    palette: ["#F0D8B8", "#D89080", "#A04858"],
    occasions: ["date","party","brunch","festival"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Bold Glam",
    emoji: "💋",
    desc: "Sculpted cheeks, smokey halo eye, sharp wing, full lashes, classic red lip.",
    palette: ["#E8B098", "#A85048", "#8C1A1A"],
    occasions: ["party","wedding","date","festival"],
    weather: ["any","cold"],
    styles: ["fancy","stylish"],
    presentations: ["feminine"],
  },
  {
    name: "Smokey Eyes",
    emoji: "🖤",
    desc: "Diffused charcoal smoke, kohl waterline, glossy nude lip — eyes do the talking.",
    palette: ["#3A2A30", "#6A4858", "#D8B098"],
    occasions: ["party","date","festival"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Bridal Radiance",
    emoji: "👰",
    desc: "Long-wear luminous base, jewel-tone eye, pop of highlight, plush berry lip.",
    palette: ["#F8D8B8", "#C06078", "#8A2848"],
    occasions: ["wedding","festival"],
    weather: ["any"],
    styles: ["fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Festive Kohl & Bindi",
    emoji: "🪔",
    desc: "Deep kohl-rimmed eyes, gold-shimmer lid, statement bindi, warm berry lip.",
    palette: ["#F0C898", "#B85040", "#5A1830"],
    occasions: ["festival","wedding"],
    weather: ["any","cold","humid"],
    styles: ["stylish","fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Sun-Kissed Bronzed",
    emoji: "🌞",
    desc: "Bronzer-forward base, glossy lid, freckled cheeks, peach-nude lip.",
    palette: ["#F0C8A0", "#C88058", "#8C5028"],
    occasions: ["beach","brunch","casual","festival"],
    weather: ["sunny","humid"],
    styles: ["comfy","stylish"],
    presentations: ["feminine"],
  },
  {
    name: "Classic Red Lip",
    emoji: "❤️",
    desc: "Clean skin, mascara, a precisely lined true-red lip — timeless statement.",
    palette: ["#F5D8C0", "#D85850", "#9C1020"],
    occasions: ["date","party","work","wedding"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Rosy Romantic",
    emoji: "🌹",
    desc: "Flushed cream blush blended onto lids and lips, fluttery lashes, glossy finish.",
    palette: ["#FFD8D0", "#F0809C", "#B83860"],
    occasions: ["date","brunch","wedding"],
    weather: ["any","cold","sunny"],
    styles: ["stylish","fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Cool Office Polish",
    emoji: "🧊",
    desc: "Even matte skin, soft taupe shadow, defined lash line, my-lips-but-better.",
    palette: ["#EBD8C8", "#A89080", "#6A5048"],
    occasions: ["work","interview"],
    weather: ["any","cold","humid"],
    styles: ["simple","stylish"],
    presentations: ["feminine"],
  },

  // Masculine grooming
  {
    name: "Clean Shave & Skin Balm",
    emoji: "🪒",
    desc: "Close shave, soothing balm, brow tidy, a swipe of lip balm — polished from skin out.",
    palette: ["#F0DCC8", "#C89880", "#6A4838"],
    occasions: ["interview","work","wedding","date"],
    weather: ["any","cold","humid"],
    styles: ["simple","stylish","fancy"],
    presentations: ["masculine"],
  },
  {
    name: "Sculpted Beard & Brows",
    emoji: "🧔",
    desc: "Lined beard with a clean neckline, brushed brows, hydrated skin, matte finish.",
    palette: ["#E8C8A8", "#8A5838", "#3A2820"],
    occasions: ["date","party","brunch","festival","wedding"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["masculine"],
  },
  {
    name: "Sharp Stubble Edge-Up",
    emoji: "✂️",
    desc: "Crisp stubble line, matte SPF, balmed lips — modern, sharp, low-effort.",
    palette: ["#F0D8C0", "#A87858", "#503830"],
    occasions: ["casual","brunch","date","work"],
    weather: ["any","humid","sunny"],
    styles: ["stylish","simple"],
    presentations: ["masculine"],
  },
  {
    name: "Festive Kohl Liner",
    emoji: "🖤",
    desc: "Subtle smudged kohl on the lower lash line, hydrated skin, glossy lip — quietly dramatic.",
    palette: ["#3A2A30", "#7A4858", "#E0B098"],
    occasions: ["festival","wedding","party","date"],
    weather: ["any","cold"],
    styles: ["fancy","stylish"],
    presentations: ["masculine"],
  },
  {
    name: "Hydrated Glow",
    emoji: "💧",
    desc: "Hydrating serum, lightweight SPF, brushed-up brows, balmy lips — that 'good skin' look.",
    palette: ["#FFE8D8", "#E8B898", "#A87858"],
    occasions: ["brunch","casual","beach","gym","interview"],
    weather: ["sunny","humid","any"],
    styles: ["simple","comfy"],
    presentations: ["masculine","androgynous"],
  },
  {
    name: "Athletic Sun Shield",
    emoji: "🌞",
    desc: "Sweatproof SPF, lip sun balm, clean groomed brows — built for sweat and sun.",
    palette: ["#FFE0C8", "#D89060", "#8C5028"],
    occasions: ["gym","beach","casual","brunch"],
    weather: ["sunny","humid","rainy"],
    styles: ["simple","comfy"],
    presentations: ["masculine","androgynous"],
  },

  // Androgynous / any
  {
    name: "Waterproof Fresh",
    emoji: "💦",
    desc: "Sweat-proof tint, water-resistant mascara, stained lip — built to survive the day.",
    palette: ["#F8D0BC", "#D87868", "#B04848"],
    occasions: ["beach","gym","casual","brunch"],
    weather: ["rainy","humid","sunny"],
    styles: ["comfy","simple"],
    presentations: ["feminine","androgynous"],
  },
  {
    name: "No-Makeup Makeup",
    emoji: "🌱",
    desc: "Skin tint where needed, brow gel, clear mascara, lip balm — you, just rested.",
    palette: ["#F8E0D0", "#E8B098", "#B07868"],
    occasions: ["gym","casual","brunch","beach"],
    weather: ["humid","sunny","rainy"],
    styles: ["simple","comfy"],
    presentations: ["any"],
  },
  {
    name: "Clean Skin & Brows",
    emoji: "🪞",
    desc: "Tinted moisturizer, brushed brows, balm — the universal 'well-rested' look.",
    palette: ["#FAE2D0", "#D8AC90", "#8A5840"],
    occasions: ["interview","work","brunch","casual","date"],
    weather: ["any","cold","humid"],
    styles: ["simple","stylish"],
    presentations: ["any"],
  },
  {
    name: "Glossy Lip Pop",
    emoji: "💄",
    desc: "Skin left bare and healthy, just a single high-shine tinted lip — neutral and bold at once.",
    palette: ["#F5D8C8", "#E07880", "#A03048"],
    occasions: ["party","date","casual","brunch"],
    weather: ["any","cold","sunny"],
    styles: ["stylish","fancy"],
    presentations: ["androgynous","feminine"],
  },
];

// ----- JEWELLERY -----
window.JEWELLERY = [
  // Universal
  {
    name: "Minimal Studs",
    emoji: "✨",
    desc: "Tiny gold or pearl studs — barely-there shine that works with anything.",
    occasions: ["work","interview","gym","casual","brunch"],
    weather: ["any"],
    styles: ["simple","comfy"],
    presentations: ["any"],
  },
  {
    name: "Delicate Gold Chain",
    emoji: "🪙",
    desc: "A fine layered chain or single pendant — soft glint at the collarbone.",
    occasions: ["brunch","date","work","casual","interview"],
    weather: ["any"],
    styles: ["simple","stylish"],
    presentations: ["any"],
  },
  {
    name: "Stacked Bracelets",
    emoji: "📿",
    desc: "Mixed metals, a watch, a few beaded strands — wrist party of one.",
    occasions: ["brunch","party","casual","festival"],
    weather: ["any","sunny"],
    styles: ["stylish","comfy"],
    presentations: ["any"],
  },
  {
    name: "Watch + Nothing Else",
    emoji: "⌚",
    desc: "A clean watch and bare everything else — pure, deliberate minimalism.",
    occasions: ["work","interview","gym","casual"],
    weather: ["any"],
    styles: ["simple"],
    presentations: ["any"],
  },
  {
    name: "Shell & Bead Layers",
    emoji: "🐚",
    desc: "Layered shell, wood, and seed-bead strands — sun-and-salt boho.",
    occasions: ["beach","casual","festival","brunch"],
    weather: ["sunny","humid"],
    styles: ["comfy","stylish"],
    presentations: ["any"],
  },

  // Feminine
  {
    name: "Classic Hoops",
    emoji: "⭕",
    desc: "Medium gold hoops — instantly pulls an outfit together.",
    occasions: ["brunch","casual","date","party","festival"],
    weather: ["any"],
    styles: ["stylish","comfy"],
    presentations: ["feminine"],
  },
  {
    name: "Pearl Set",
    emoji: "🦪",
    desc: "Pearl studs and a delicate strand — refined, soft, and quietly luxurious.",
    occasions: ["wedding","work","interview","brunch","date"],
    weather: ["any"],
    styles: ["stylish","fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Statement Earrings",
    emoji: "💎",
    desc: "Sculptural drops or chandeliers — let the ears do the heavy lifting.",
    occasions: ["party","date","wedding","festival"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Kundan / Polki Set",
    emoji: "👑",
    desc: "Heritage stones, gold setting — bridal-grade sparkle for the biggest moments.",
    occasions: ["wedding","festival"],
    weather: ["any"],
    styles: ["fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Oxidized Silver Jhumkas",
    emoji: "🔔",
    desc: "Tribal silver bells with a swing — earthy, festive, full of character.",
    occasions: ["festival","brunch","casual","date"],
    weather: ["any","humid","cold"],
    styles: ["stylish"],
    presentations: ["feminine"],
  },
  {
    name: "Choker Necklace",
    emoji: "🖤",
    desc: "Sleek velvet, leather, or metal choker — sharp and a little daring.",
    occasions: ["party","date","festival"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["feminine","androgynous"],
  },
  {
    name: "Cuff Bangles",
    emoji: "💫",
    desc: "Wide gold cuffs or kada stacks — architectural and unmistakably festive.",
    occasions: ["wedding","festival","party"],
    weather: ["any"],
    styles: ["fancy","stylish"],
    presentations: ["feminine"],
  },
  {
    name: "Anklet & Toe Ring",
    emoji: "🐚",
    desc: "Delicate ankle chain with a tiny charm — perfect with bare feet or sandals.",
    occasions: ["beach","festival","casual","brunch"],
    weather: ["sunny","humid"],
    styles: ["comfy","stylish"],
    presentations: ["feminine"],
  },
  {
    name: "Maang Tikka + Earrings",
    emoji: "🌟",
    desc: "Forehead piece paired with matched earrings — instant ceremony energy.",
    occasions: ["wedding","festival"],
    weather: ["any"],
    styles: ["fancy"],
    presentations: ["feminine"],
  },

  // Masculine
  {
    name: "Signet Ring + Watch",
    emoji: "💍",
    desc: "A weighty signet on the pinky, a refined watch on the wrist — quiet authority.",
    occasions: ["work","interview","date","wedding","brunch"],
    weather: ["any"],
    styles: ["simple","stylish","fancy"],
    presentations: ["masculine","androgynous"],
  },
  {
    name: "Leather Cord Pendant",
    emoji: "🧿",
    desc: "Single pendant on a slim leather cord — grounded, lived-in, and personal.",
    occasions: ["casual","brunch","festival","beach","date"],
    weather: ["any","sunny","humid"],
    styles: ["comfy","stylish"],
    presentations: ["masculine","androgynous"],
  },
  {
    name: "Cufflinks + Tie Pin",
    emoji: "🎯",
    desc: "Polished cufflinks and a subtle tie pin — the formal-wear power move.",
    occasions: ["wedding","interview","work","party"],
    weather: ["any","cold"],
    styles: ["fancy","stylish"],
    presentations: ["masculine"],
  },
  {
    name: "Beaded Bracelet Stack",
    emoji: "🟤",
    desc: "Wooden, rudraksh, or stone beads stacked on one wrist — earthy and unfussy.",
    occasions: ["casual","brunch","festival","beach","gym"],
    weather: ["any","sunny","humid"],
    styles: ["comfy","stylish"],
    presentations: ["masculine","androgynous"],
  },
  {
    name: "Chunky Chain Necklace",
    emoji: "🔗",
    desc: "A bold curb or rope chain — confident statement on a plain tee or open shirt.",
    occasions: ["party","date","casual","festival"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["masculine","androgynous"],
  },
  {
    name: "Brooch on Lapel",
    emoji: "🌺",
    desc: "A single sculptural brooch pinned to a jacket lapel — heritage meets editorial.",
    occasions: ["wedding","festival","party"],
    weather: ["any","cold"],
    styles: ["fancy"],
    presentations: ["masculine"],
  },
];

// ----- CLOTHING -----
window.CLOTHING = [
  // Universal
  {
    name: "Crisp Shirt + Trousers",
    emoji: "👔",
    desc: "Ironed white or pastel shirt tucked into tailored trousers, slim belt, loafers.",
    occasions: ["interview","work"],
    weather: ["any","humid","cold"],
    styles: ["simple","stylish"],
    presentations: ["any"],
  },
  {
    name: "Linen Co-ord Set",
    emoji: "🥥",
    desc: "Matching linen top and pants in cream or sage — breathes beautifully in heat.",
    occasions: ["brunch","beach","casual","festival"],
    weather: ["sunny","humid"],
    styles: ["comfy","stylish"],
    presentations: ["any"],
  },
  {
    name: "Athleisure Set",
    emoji: "🏃",
    desc: "Sculpting bottoms, supportive top, oversized tee, fresh trainers.",
    occasions: ["gym","casual"],
    weather: ["any","humid"],
    styles: ["comfy","simple"],
    presentations: ["any"],
  },
  {
    name: "Trench Coat + Boots",
    emoji: "🧥",
    desc: "Belted trench over a knit and slim jeans, ankle boots, compact umbrella.",
    occasions: ["work","date","casual","brunch"],
    weather: ["rainy","cold"],
    styles: ["stylish","simple"],
    presentations: ["any"],
  },
  {
    name: "Denim + Fresh White Tee",
    emoji: "👖",
    desc: "Well-fitted jeans, a perfect white tee, sneakers, a tossed-on blazer or jacket.",
    occasions: ["casual","brunch","date"],
    weather: ["any","cold"],
    styles: ["simple","comfy"],
    presentations: ["any"],
  },
  {
    name: "Oversized Hoodie + Joggers",
    emoji: "🧦",
    desc: "Boxy hoodie, tapered joggers, fresh sneakers — peak comfort, still put together.",
    occasions: ["casual","gym","brunch"],
    weather: ["cold","rainy","any"],
    styles: ["comfy"],
    presentations: ["any"],
  },

  // Feminine
  {
    name: "Tailored Pantsuit",
    emoji: "🧥",
    desc: "Crisp blazer over matching trousers, fitted tee underneath, pointed flats or block heels.",
    occasions: ["interview","work","party"],
    weather: ["any","cold","rainy"],
    styles: ["stylish","fancy"],
    presentations: ["feminine","androgynous"],
  },
  {
    name: "Blazer + Midi Skirt",
    emoji: "🧶",
    desc: "Structured blazer with a sleek midi skirt, fitted top, and elegant pumps.",
    occasions: ["work","interview","date","brunch"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Pastel Saree",
    emoji: "🌸",
    desc: "Flowing chiffon or silk saree in a soft pastel, embellished blouse, pinned pallu.",
    occasions: ["wedding","festival"],
    weather: ["any","humid","cold"],
    styles: ["fancy","stylish"],
    presentations: ["feminine"],
  },
  {
    name: "Embroidered Lehenga",
    emoji: "💃",
    desc: "Flared embroidered lehenga, fitted choli, sheer dupatta draped over one shoulder.",
    occasions: ["wedding","festival"],
    weather: ["any","cold"],
    styles: ["fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Anarkali Suit",
    emoji: "🪷",
    desc: "Floor-grazing anarkali with churidar and a light dupatta — graceful and festive.",
    occasions: ["festival","wedding","date"],
    weather: ["any","cold"],
    styles: ["fancy","stylish"],
    presentations: ["feminine"],
  },
  {
    name: "Kurta + Palazzo",
    emoji: "🌼",
    desc: "Breezy kurta over wide palazzos, dupatta optional — easy ethnic everyday.",
    occasions: ["festival","casual","brunch","work"],
    weather: ["humid","sunny","any"],
    styles: ["simple","comfy"],
    presentations: ["feminine"],
  },
  {
    name: "Floral Maxi Dress",
    emoji: "🌷",
    desc: "Flowy maxi in a print, cinched waist, strappy sandals — sundress energy.",
    occasions: ["brunch","date","casual","beach"],
    weather: ["sunny","humid"],
    styles: ["comfy","stylish"],
    presentations: ["feminine"],
  },
  {
    name: "Little Black Dress",
    emoji: "🖤",
    desc: "Sleek fitted LBD, killer heels, simple clutch — a forever winner.",
    occasions: ["date","party","wedding"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Sequin Cocktail Dress",
    emoji: "🪩",
    desc: "Shimmering body-skimming mini, strappy heels, dramatic earrings — main character.",
    occasions: ["party","wedding"],
    weather: ["any","cold"],
    styles: ["fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Boho Skirt + Crop Top",
    emoji: "🌻",
    desc: "Tiered maxi skirt, fitted crop top, layered necklaces, ankle boots or sandals.",
    occasions: ["festival","casual","brunch","date"],
    weather: ["sunny","humid","any"],
    styles: ["stylish","comfy"],
    presentations: ["feminine"],
  },
  {
    name: "Wool Sweater Dress",
    emoji: "🧣",
    desc: "Cozy knit dress, opaque tights, knee boots, oversized scarf — winter armor.",
    occasions: ["casual","date","brunch","work"],
    weather: ["cold"],
    styles: ["comfy","stylish"],
    presentations: ["feminine"],
  },
  {
    name: "Sundress + Straw Hat",
    emoji: "🌞",
    desc: "Light cotton sundress, wide-brim straw hat, slide sandals — beach uniform.",
    occasions: ["beach","casual","brunch"],
    weather: ["sunny","humid"],
    styles: ["comfy","simple"],
    presentations: ["feminine"],
  },
  {
    name: "Bodycon Mini",
    emoji: "💋",
    desc: "Ribbed body-skimming mini, sleek heels, statement earrings — pure night-out.",
    occasions: ["party","date"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["feminine"],
  },

  // Masculine
  {
    name: "Tailored Two-Piece Suit",
    emoji: "🤵",
    desc: "Slim-cut suit in navy or charcoal, crisp shirt, silk tie, oxford shoes.",
    occasions: ["wedding","interview","work","party"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["masculine"],
  },
  {
    name: "Three-Piece Tuxedo",
    emoji: "🎩",
    desc: "Black tux with satin lapels, white dress shirt, bow tie, pocket square — formal apex.",
    occasions: ["wedding","party"],
    weather: ["any","cold"],
    styles: ["fancy"],
    presentations: ["masculine"],
  },
  {
    name: "Sherwani",
    emoji: "👑",
    desc: "Embroidered sherwani over churidar with mojaris and a draped stole — ceremony icon.",
    occasions: ["wedding","festival"],
    weather: ["any","cold"],
    styles: ["fancy"],
    presentations: ["masculine"],
  },
  {
    name: "Bandhgala Jacket",
    emoji: "🪷",
    desc: "Structured bandhgala over trousers, pocket square — Indo-Western sharp.",
    occasions: ["wedding","festival","party"],
    weather: ["any","cold"],
    styles: ["fancy","stylish"],
    presentations: ["masculine"],
  },
  {
    name: "Kurta + Churidar",
    emoji: "🪔",
    desc: "Cotton or silk kurta over slim churidar with juttis — festive but breathable.",
    occasions: ["festival","wedding","casual","brunch"],
    weather: ["any","humid","sunny"],
    styles: ["stylish","simple","fancy"],
    presentations: ["masculine"],
  },
  {
    name: "Pathani Suit",
    emoji: "🕌",
    desc: "Long pathani kurta with matching trousers — laid-back ethnic with edge.",
    occasions: ["festival","casual","wedding"],
    weather: ["any","humid","cold"],
    styles: ["comfy","stylish"],
    presentations: ["masculine"],
  },
  {
    name: "Linen Shirt + Trousers",
    emoji: "🌾",
    desc: "Breathable linen shirt half-tucked into pleated trousers, loafers or sandals.",
    occasions: ["brunch","beach","casual","date"],
    weather: ["sunny","humid"],
    styles: ["comfy","stylish","simple"],
    presentations: ["masculine","androgynous"],
  },
  {
    name: "Henley + Chinos",
    emoji: "☕",
    desc: "Soft henley, slim chinos, white sneakers, a watch — easy, considered everyday.",
    occasions: ["casual","brunch","date","work"],
    weather: ["any","sunny","cold"],
    styles: ["simple","comfy","stylish"],
    presentations: ["masculine","androgynous"],
  },
  {
    name: "Bomber + Joggers",
    emoji: "🧢",
    desc: "Tech bomber, tapered joggers, chunky trainers — streetwear-ready.",
    occasions: ["casual","gym","party"],
    weather: ["cold","rainy","any"],
    styles: ["comfy","stylish"],
    presentations: ["masculine","androgynous"],
  },
  {
    name: "Wool Overcoat + Roll Neck",
    emoji: "🧊",
    desc: "Long wool overcoat over a fine-knit roll neck and dark trousers, leather boots.",
    occasions: ["work","date","casual","brunch"],
    weather: ["cold"],
    styles: ["stylish","fancy"],
    presentations: ["masculine","androgynous"],
  },
  {
    name: "Polo + Tailored Shorts",
    emoji: "🌴",
    desc: "Fitted polo, tailored above-knee shorts, leather sliders or loafers.",
    occasions: ["beach","brunch","casual"],
    weather: ["sunny","humid"],
    styles: ["comfy","stylish","simple"],
    presentations: ["masculine"],
  },
  {
    name: "Bold Print Shirt + Trousers",
    emoji: "🌺",
    desc: "Statement-print shirt, undone top button, monochrome trousers, suede loafers.",
    occasions: ["party","date","festival","brunch"],
    weather: ["any","sunny","humid"],
    styles: ["stylish","fancy"],
    presentations: ["masculine"],
  },
];

// ----- HAIRSTYLE -----
window.HAIRSTYLE = [
  // Universal
  {
    name: "Top Knot",
    emoji: "🍡",
    desc: "Hair scraped up into a high knot — off-the-neck and instantly fresh.",
    occasions: ["gym","casual","beach","brunch","festival"],
    weather: ["humid","sunny","rainy"],
    styles: ["comfy","simple","stylish"],
    presentations: ["any"],
  },
  {
    name: "Air-Dried Natural",
    emoji: "💨",
    desc: "Your texture, lightly defined with a curl cream or smoothing serum — confident as-is.",
    occasions: ["casual","beach","gym","brunch"],
    weather: ["any","humid","sunny"],
    styles: ["simple","comfy"],
    presentations: ["any"],
  },
  {
    name: "Slick Back",
    emoji: "🐎",
    desc: "Wet-look gelled crown swept straight back — sleek, modern, weather-proof.",
    occasions: ["party","work","date","wedding","interview"],
    weather: ["rainy","humid","any"],
    styles: ["stylish","fancy"],
    presentations: ["any"],
  },
  {
    name: "Twist Outs",
    emoji: "🌀",
    desc: "Defined twist-out curls, picked out for volume — celebrates natural texture.",
    occasions: ["casual","brunch","date","party","festival"],
    weather: ["any","humid"],
    styles: ["stylish","comfy"],
    presentations: ["any"],
  },

  // Feminine
  {
    name: "Sleek Low Bun",
    emoji: "🌀",
    desc: "Center part, slick-back, polished low bun at the nape — clean and authoritative.",
    occasions: ["interview","work","wedding","party"],
    weather: ["humid","rainy","any"],
    styles: ["simple","stylish","fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Soft Beach Waves",
    emoji: "🌊",
    desc: "Loose tousled waves, slight middle part, ends finger-combed — effortless cool.",
    occasions: ["brunch","date","casual","party","beach"],
    weather: ["sunny","any","cold"],
    styles: ["stylish","comfy"],
    presentations: ["feminine"],
  },
  {
    name: "High Ponytail",
    emoji: "🎀",
    desc: "Sky-high pony with a smooth crown, ends curled or sleek — instantly lifted.",
    occasions: ["gym","casual","party","date"],
    weather: ["humid","sunny","any"],
    styles: ["stylish","comfy","simple"],
    presentations: ["feminine"],
  },
  {
    name: "Messy Low Bun",
    emoji: "🧁",
    desc: "Knotted low bun with face-framing pieces pulled out — looks like 30 seconds, reads chic.",
    occasions: ["casual","brunch","gym","work"],
    weather: ["any","humid"],
    styles: ["comfy","simple"],
    presentations: ["feminine"],
  },
  {
    name: "Half-Up Half-Down",
    emoji: "🎗️",
    desc: "Top section pulled back into a clip or twist, the rest left soft and loose.",
    occasions: ["brunch","date","casual","wedding"],
    weather: ["any","cold"],
    styles: ["stylish","comfy"],
    presentations: ["feminine"],
  },
  {
    name: "Braided Crown",
    emoji: "👑",
    desc: "Two braids wrapped over the crown like a halo — romantic and a little regal.",
    occasions: ["festival","wedding","brunch"],
    weather: ["any","sunny","humid"],
    styles: ["stylish","fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Side-Swept Curls",
    emoji: "💫",
    desc: "Voluminous curls pushed to one shoulder, pinned discreetly — old-Hollywood drama.",
    occasions: ["party","wedding","date"],
    weather: ["any","cold"],
    styles: ["fancy","stylish"],
    presentations: ["feminine"],
  },
  {
    name: "Sleek Straight",
    emoji: "📏",
    desc: "Glassy, flat-iron-straight hair with a deep part — sharp and modern.",
    occasions: ["work","interview","party","date"],
    weather: ["any","cold"],
    styles: ["stylish","simple"],
    presentations: ["feminine"],
  },
  {
    name: "Fishtail Braid",
    emoji: "🐟",
    desc: "One long fishtail down the back or over the shoulder, slightly tugged loose.",
    occasions: ["festival","beach","casual","brunch"],
    weather: ["sunny","humid","any"],
    styles: ["stylish","comfy"],
    presentations: ["feminine"],
  },
  {
    name: "Floral Bun (Gajra)",
    emoji: "🌺",
    desc: "Smooth bun wrapped in jasmine or rose strands — ceremony in a hairstyle.",
    occasions: ["wedding","festival"],
    weather: ["any","cold","humid"],
    styles: ["fancy"],
    presentations: ["feminine"],
  },
  {
    name: "Loose Bouncy Curls",
    emoji: "🌸",
    desc: "Big soft barrel curls, brushed out for volume — feminine and full of movement.",
    occasions: ["date","party","brunch","wedding"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["feminine"],
  },

  // Masculine
  {
    name: "Sharp Side Part",
    emoji: "📐",
    desc: "Clean side parting, taper at the sides, polished comb-over — boardroom classic.",
    occasions: ["interview","work","wedding","date"],
    weather: ["any","cold"],
    styles: ["simple","stylish","fancy"],
    presentations: ["masculine"],
  },
  {
    name: "Textured Crop",
    emoji: "🌿",
    desc: "Short, choppy top with a faded back and sides — low-maintenance, high-impact.",
    occasions: ["casual","date","brunch","work","gym"],
    weather: ["any","humid","sunny"],
    styles: ["stylish","comfy","simple"],
    presentations: ["masculine"],
  },
  {
    name: "Tapered Fade + Curls",
    emoji: "🌪️",
    desc: "Faded sides into a defined curly top — sharp lines, celebrated texture.",
    occasions: ["casual","date","party","brunch","festival"],
    weather: ["any","humid"],
    styles: ["stylish","comfy"],
    presentations: ["masculine"],
  },
  {
    name: "Modern Quiff",
    emoji: "🎤",
    desc: "Volume swept up and back, a slight forward flick at the front — confident and dressy.",
    occasions: ["wedding","date","party","interview"],
    weather: ["any","cold"],
    styles: ["stylish","fancy"],
    presentations: ["masculine"],
  },
  {
    name: "Buzz Cut",
    emoji: "🪖",
    desc: "Uniform short crop — clean, fuss-free, and lets features take center stage.",
    occasions: ["gym","casual","work","interview"],
    weather: ["any","humid","sunny"],
    styles: ["simple","comfy"],
    presentations: ["masculine"],
  },
  {
    name: "Man Bun",
    emoji: "🍩",
    desc: "Long hair gathered into a low or mid bun, a few face-framing strands loose.",
    occasions: ["festival","casual","beach","brunch","date"],
    weather: ["sunny","humid","any"],
    styles: ["stylish","comfy"],
    presentations: ["masculine","androgynous"],
  },
  {
    name: "Pompadour",
    emoji: "🎙️",
    desc: "High volume at the front, polished back into a sleek crown — retro icon energy.",
    occasions: ["wedding","party","date"],
    weather: ["any","cold"],
    styles: ["fancy","stylish"],
    presentations: ["masculine"],
  },
  {
    name: "Cropped Curtains",
    emoji: "🌬️",
    desc: "Middle-parted fringe that frames the face, faded back and sides — modern soft boy.",
    occasions: ["casual","date","brunch","festival","party"],
    weather: ["any","cold"],
    styles: ["stylish","comfy"],
    presentations: ["masculine"],
  },
];
